# Generated by Django 2.2.3 on 2019-07-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='taker',
        ),
        migrations.AddField(
            model_name='character',
            name='friend',
            field=models.ManyToManyField(related_name='_character_friend_+', to='village_app.Character'),
        ),
    ]
